# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e789dca46952a8fbe9d046566f066b865862cab758ad6cf1185f4e469d9dffee49c9583cb16929a554179368cfd18d45bebc07c5419e9a668517e9794277d0e0

test:
  secret_key_base: 43e870fa08b3e0a712205a7fb31753954702be7dd1bfe709b8f9bc3f8da8ef698ca56fff31caaa8128af55b78395a6e5e7f19fd3ceb69afcaabd79795d1a38df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
